### ISSUE TITLE
Include build_runner for ORM

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/cli#71]

**Comment by thosakwe** [comment]
Users could just run `angel build`, or `angel build --watch`, instead of adding all the `package:build` boilerplate.

They could also include a simple config file:

```yaml
# angel_build.yaml
serialize:
  - lib/src/models/**/*.dart
orm:
  standalone:
    - lib/src/models/author.dart
    - lib/src/models/consumer.dart
  dependent:
    - lib/src/models/dependent/*.dart
```

All three boilerplates would be modified to include a similar boilerplate file.
